import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import JSZip from 'jszip';
import type { ListingResult } from './listingService';
import type { AdVariation } from '../constants';

export type ExportPlatform = 'full' | 'etsy' | 'amazon' | 'shopify' | 'instagram' | 'tiktok';

export const EXPORT_PRESETS: {
  id: ExportPlatform;
  label: string;
  includes: string[];
}[] = [
  {
    id: 'full',
    label: 'Full Pack',
    includes: ['6 images', 'Etsy, Amazon, Shopify copy', 'Instagram & TikTok content', 'instructions.txt'],
  },
  {
    id: 'etsy',
    label: 'Etsy Seller',
    includes: ['6 images', 'etsy-listing.txt', 'instructions.txt'],
  },
  {
    id: 'amazon',
    label: 'Amazon Seller',
    includes: ['6 images', 'amazon-listing.txt', 'instructions.txt'],
  },
  {
    id: 'shopify',
    label: 'Shopify Store',
    includes: ['6 images', 'shopify-product.txt', 'instructions.txt'],
  },
  {
    id: 'instagram',
    label: 'Instagram',
    includes: ['6 images', 'instagram-caption.txt', 'instructions.txt'],
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    includes: ['6 images', 'tiktok-content.txt', 'instructions.txt'],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function extractBase64(dataUri: string): string {
  return dataUri.startsWith('data:') ? dataUri.split(',')[1] : dataUri;
}

// ─── Copy builders ────────────────────────────────────────────────────────────

function buildEtsyTxt(l: ListingResult): string {
  const d = l.etsy.description;
  const sections = [
    d.intro,
    d.details,
    d.materials && `MATERIALS\n${d.materials}`,
    d.care && `CARE\n${d.care}`,
    d.shipping && `SHIPPING\n${d.shipping}`,
    d.gift && `GIFT\n${d.gift}`,
  ].filter(Boolean).join('\n\n');

  return [
    'ETSY LISTING',
    '═══════════════════════════════',
    '',
    'TITLE',
    l.etsy.title,
    '',
    'TAGS (paste directly into Etsy tag fields)',
    l.etsy.tags.join(', '),
    '',
    'DESCRIPTION',
    sections,
    '',
    'KEYWORDS',
    l.global.keywords.join(', '),
  ].join('\n');
}

function buildAmazonTxt(l: ListingResult): string {
  return [
    'AMAZON LISTING',
    '═══════════════════════════════',
    '',
    'TITLE',
    l.amazon.title,
    '',
    'BULLET POINTS',
    ...l.amazon.bullets.map(b => `• ${b}`),
    '',
    'DESCRIPTION',
    l.amazon.description,
    '',
    'BACKEND KEYWORDS (hidden SEO)',
    l.amazon.backend_keywords.join(', '),
  ].join('\n');
}

function buildShopifyTxt(l: ListingResult): string {
  return [
    'SHOPIFY PRODUCT',
    '═══════════════════════════════',
    '',
    'TITLE',
    l.global.title,
    '',
    'SHORT DESCRIPTION',
    l.global.short_description,
    '',
    'LONG DESCRIPTION',
    l.global.long_description,
    '',
    'BULLET POINTS',
    ...l.amazon.bullets.map(b => `• ${b}`),
    '',
    'KEYWORDS / TAGS',
    l.global.keywords.join(', '),
  ].join('\n');
}

function buildInstagramTxt(l: ListingResult): string {
  return [
    'INSTAGRAM CONTENT',
    '═══════════════════════════════',
    '',
    'CAPTION',
    l.instagram.caption,
    '',
    'HASHTAGS',
    l.instagram.hashtags.join(' '),
  ].join('\n');
}

function buildTikTokTxt(l: ListingResult): string {
  return [
    'TIKTOK CONTENT',
    '═══════════════════════════════',
    '',
    'HOOK (opening line / on-screen text)',
    l.tiktok.hook,
    '',
    'CAPTION',
    l.tiktok.caption,
    '',
    'HASHTAGS',
    l.tiktok.hashtags.join(' '),
  ].join('\n');
}

// ─── Instructions ─────────────────────────────────────────────────────────────

function buildInstructions(platform: ExportPlatform): string {
  const name = { full: 'All Platforms', etsy: 'Etsy', amazon: 'Amazon', shopify: 'Shopify', instagram: 'Instagram', tiktok: 'TikTok' }[platform];
  return `ADGENIUS AI — EXPORT PACK
Generated for: ${name}
Date: ${new Date().toLocaleDateString()}
════════════════════════════════════

IMAGES FOLDER
• AI-generated product images, ready to upload
• Use "01-main-shot" or "05-studio-stand" as your primary listing image
• "06-lifestyle-scene" and "02-in-context" work best for Instagram/TikTok

COPY FOLDER
• Platform-optimized text files — open any .txt file to read your listing copy
• Copy and paste directly into Etsy, Amazon, Shopify, or social apps
• Review for accuracy before publishing

TIPS
• Open .txt files in Notes or any text editor
• For Etsy: copy tags from etsy-listing.txt, paste one-by-one into tag fields
• For Amazon: bullet points start with ALL-CAPS lead phrases
• For Shopify: paste the Long Description into the product body field
• Need CSV import files? Use the Nexio web app on your computer

Generated by Nexio AI`;
}

// ─── Main export ──────────────────────────────────────────────────────────────

const IMAGE_NAMES: Record<string, string> = {
  main_shot: '01-main-shot',
  human_interaction: '02-in-context',
  hand_held: '03-hand-held',
  macro_detail: '04-macro-detail',
  studio_stand: '05-studio-stand',
  lifestyle_scene: '06-lifestyle-scene',
};

export async function exportProductKit(
  variations: AdVariation[],
  listing: ListingResult,
  platform: ExportPlatform,
): Promise<void> {
  const zip = new JSZip();

  // Images — handle both base64 data URIs and remote HTTPS URLs
  const completed = variations.filter(v => v.status === 'completed' && v.imageUrl);
  for (const v of completed) {
    const name = IMAGE_NAMES[v.type] ?? `image-${v.type}`;
    let b64: string;
    if (v.imageUrl!.startsWith('http')) {
      const tmpUri = `${FileSystem.cacheDirectory}nexio_exp_${v.type}_${Date.now()}.jpg`;
      await FileSystem.downloadAsync(v.imageUrl!, tmpUri);
      b64 = await FileSystem.readAsStringAsync(tmpUri, { encoding: FileSystem.EncodingType.Base64 });
      await FileSystem.deleteAsync(tmpUri, { idempotent: true });
    } else {
      b64 = extractBase64(v.imageUrl!);
    }
    zip.file(`images/${name}.jpg`, b64, { base64: true });
  }

  // Copy files
  const all = platform === 'full';
  if (all || platform === 'etsy')      zip.file('copy/etsy-listing.txt',      buildEtsyTxt(listing));
  if (all || platform === 'amazon')    zip.file('copy/amazon-listing.txt',    buildAmazonTxt(listing));
  if (all || platform === 'shopify')   zip.file('copy/shopify-product.txt',   buildShopifyTxt(listing));
  if (all || platform === 'instagram') zip.file('copy/instagram-caption.txt', buildInstagramTxt(listing));
  if (all || platform === 'tiktok')    zip.file('copy/tiktok-content.txt',    buildTikTokTxt(listing));

  // Instructions
  zip.file('instructions.txt', buildInstructions(platform));

  // Build ZIP
  const zipBase64 = await zip.generateAsync({
    type: 'base64',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  // Write to cache
  const fileName = `nexio-${platform}-${Date.now()}.zip`;
  const fileUri = `${FileSystem.cacheDirectory}${fileName}`;
  await FileSystem.writeAsStringAsync(fileUri, zipBase64, {
    encoding: FileSystem.EncodingType.Base64,
  });

  // Share
  await Sharing.shareAsync(fileUri, {
    mimeType: 'application/zip',
    dialogTitle: 'Save your Product Kit',
    UTI: 'public.zip-archive',
  });
}
